# Generated by Django 3.2.18 on 2023-03-10 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0004_auto_20230310_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='serving',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
