# Generated by Django 3.2.18 on 2023-03-12 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0005_recipe_serving'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='email',
        ),
    ]
